University.Web/Controllers/InstructorsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using University.BL.Models;
using University.BL.DTOs;
using University.BL.Data;
using System.Linq;
using PagedList;

namespace University.Web.Controllers
{
    public class InstructorsController : Controller
    {
        private readonly UniversityContext context = new UniversityContext();


        [HttpGet]
        public ActionResult Index(int? instructorID, int? pageSize, int? page)
        {
            #region Consluta Instructor
            var query = context.Instructors.ToList();

            var instructors = query.Where(x => x.HireDate < DateTime.Now)
                                .Select(x => new InstructorDTO
                                {
                                    ID = x.ID,
                                    FirstMidName = x.FirstMidName,
                                    LastName = x.LastName,
                                    HireDate = x.HireDate
                                }).ToList();


            #endregion


            #region Lista Instructores

            if (instructorID != null)
            {
                var deparments = (from q in context.Departments
                                  join r in context.Instructors on q.InstructorID equals r.ID
                                  where q.InstructorID == instructorID
                                  select new DepartmentDTO
                                  {

                                      DepartmentID = q.DepartmentID,
                                      Name = q.Name,
                                      Budget = q.Budget
                                  }).ToList();

                ViewBag.Deparments = deparments;
            }

            #endregion

            #region Paginacion
            //Si viene nulo dele 10 por defecto
            pageSize = (pageSize ?? 5);
            //si viene igual por defecto llevelo a la 1 
            page = (page ?? 1);
            ViewBag.pageSize = pageSize;
            #endregion 
            return View(instructors.ToPagedList(page.Value, pageSize.Value));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(InstructorDTO instructor)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(instructor);

                if (instructor.HireDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");

                //INSERT INTO Students(FirstMidName,LastName,EnrollmentDate) VALUES(@FirstMidName, @LastName, @EnrollmentDate)
                context.Instructors.Add(new Instructor
                {
                    FirstMidName = instructor.FirstMidName,
                    LastName = instructor.LastName,
                    HireDate = instructor.HireDate
                });
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(instructor);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            var instructor = context.Instructors.Where(x => x.ID == id)
                                          .Select(x => new InstructorDTO
                                          {
                                              ID = x.ID,
                                              LastName = x.LastName,
                                              FirstMidName = x.FirstMidName,
                                              HireDate = x.HireDate
                                          }).FirstOrDefault();

            return View(instructor);
        }

        [HttpPost]
        public ActionResult Edit(InstructorDTO instructor)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(instructor);

                if (instructor.HireDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");
                var instructortModel = context.Instructors.FirstOrDefault(x => x.ID == instructor.ID);

                //campos que se van a modificar
                //sobreescribo las propiedades del modelo de base de datos
                instructortModel.LastName = instructor.LastName;
                instructortModel.FirstMidName = instructor.FirstMidName;
                instructortModel.HireDate = instructor.HireDate;
                //aplique los cambios en base de datos
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(instructor);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (!context.Departments.Any(x => x.InstructorID == id))
            {
                var instructortModel = context.Instructors.FirstOrDefault(x => x.ID == id);
                context.Instructors.Remove(instructortModel);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

University.Web/Views/Instructors/Create.cshtml
@model University.BL.DTOs.InstructorDTO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>








<form action="/Instructors/Create" method="post">

    <h4>Instructor</h4>
    <hr />


    <div>
        <div class="col-4">

            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4" })
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>

        <div class="col-4">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-6" })
            @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
        </div>

        <div class="col-4">
            @Html.DisplayNameFor(m => m.HireDate )
            <input type="date" id="HireDate" name="HireDate" class="form-control">
            @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
        </div>




        <br />
        <div class="col-4">
            <button class="btn btn-success"><span><i class="fas fa-plus-circle"> </i> <input type="submit" value="Create" class="btn btn-success" /></span></button>

            @Html.ActionLink("Back to List", "Index", null, new { @class = "link" })
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }
    </div>
</form>

University.Web/Views/Instructors/Edit.cshtml
@model University.BL.DTOs.InstructorDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>



@Html.AntiForgeryToken()


    <h4>Instructor</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
<form action="/Instructors/Edit" method="post">

    @Html.HiddenFor(model => model.ID)
    <div class="col-md-4">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-6" })

        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

    </div>

    <div class="col-md-4">
        @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-6" })

        @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })

    </div>

    <div class="col-md-4">
        @Html.DisplayNameFor(m => m.HireDate)

        <input type="date" id="HireDate" name="HireDate" value="@Model.HireDateSTR" class="form-control">
        @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })

    </div>

    <br />
    <div class="col-4">
        <button class="btn btn-warning"><span><i class="fas fa-user-edit"> </i> <input type="submit" value="Edit" class="btn btn-warning" /></span></button>

        @Html.ActionLink("Back to List", "Index", null, new { @class = "link" })
    </div>

</form>

University.Web/Views/Instructors/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<University.BL.DTOs.InstructorDTO>
@{ ViewBag.Title = "Index"; }

<h2>Instructors</h2>


<button class="btn btn-secondary"><span><i class="fas fa-plus-circle"> </i>@Html.ActionLink("Create New Instructor", "Create", "Instructors", null, new { @class = "btn btn-sm btn-secondary" }) </span></button>
<hr />


<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>ID</th>
            <th>Last Name</th>
            <th>First MidName</th>
            <th>Hire Date</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.LastName</td>
                <td>@item.FirstMidName</td>
                <td>@item.HireDate.ToString("yyyy-MM-dd")</td>
                <td>
                    @Html.ActionLink("Departments", "Index", "Instructors", new { instructorID = item.ID }, new { @class = "badge btn btn-sm btn-outline-info" })
                    @Html.ActionLink("Edit", "Edit", "Instructors", new { id = item.ID }, new { @class = "badge btn btn-sm btn-outline-warning" })
                    @Html.ActionLink("Delete", "Delete", "Instructors", new { id = item.ID }, new { @class = "badge btn btn-sm btn-outline-danger" })
                </td>
            </tr>
}
    </tbody>
</table>
<div class="row">
    <div class="col-12">
        <span class="float-right">
            @using (Html.BeginForm("Index", "Instructors", FormMethod.Get))
            {

                <select name="PageSize" id="PageSize" class="form-control">
                    <option @if ((int)ViewBag.PageSize == 5) { @Html.Raw("selected") }>3</option>
                    <option @if ((int)ViewBag.PageSize == 10) { @Html.Raw("selected") }>5</option>
                    <option @if ((int)ViewBag.PageSize == 15) { @Html.Raw("selected") }>10</option>
                </select>

                <input type="submit" value="Go" class="btn btn-outline-secondary" />

            }
        </span>
    </div>
</div>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0: Model.PageNumber) of @Model.PageCount
<br />
Toatal Item Count @Model.TotalItemCount
@Html.PagedListPager(Model, page => Url.Action("Index", "Instructors", new { page, pageSize = ViewBag.PageSize }))

@if (ViewBag.Deparments != null)
{
<h1>Deparments</h1>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>DeparmentID</th>
                            <th>Name</th>
                            <th>Budget</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in (List<University.BL.DTOs.DepartmentDTO>)ViewBag.Deparments)
                        {
        <tr>
            <td>@item.DepartmentID</td>
            <td>@item.Name</td>
            <td>@item.Budget</td>

        </tr>}
                    </tbody>
                </table>}