University.Web/Controllers/CoursesController.cs
using PagedList;
using System;
using System.Linq;
using System.Web.Mvc;
using University.BL.Data;
using University.BL.DTOs;
using University.BL.Models;

namespace University.Web.Controllers
{
    public class CoursesController : Controller
    {
        private readonly UniversityContext context = new UniversityContext();
        // GET: Courses
        [HttpGet]
        public ActionResult Index(int? courseid, int? pageSize, int? page)
        {
            #region Consulta cursos
            var query = context.Courses.ToList();

            var courses = query.Select(x => new CourseDTO
            {
                CourseID = x.CourseID,
                Title = x.Title,
                Credits = x.Credits
            }).ToList();
            #endregion

            #region Listar intructores
            if (courseid != null)
            {
                var instructores = (from q in context.CourseInstructors
                                    join r in context.Courses on q.CourseID equals r.CourseID
                                    join s in context.Instructors on q.InstructorID equals s.ID
                                    where q.CourseID == courseid
                                    select new InstructorDTO
                                    {
                                        LastName = s.LastName,
                                        FirstMidName = s.FirstMidName,

                                    }).ToList();

                ViewBag.Instructores = instructores;
            }
            #endregion
            #region Paginacion
            //Si viene nulo dele 10 por defecto
            pageSize = (pageSize ?? 5);
            //si viene igual por defecto llevelo a la 1 
            page = (page ?? 1);
            ViewBag.pageSize = pageSize;
            #endregion 
            return View(courses.ToPagedList(page.Value, pageSize.Value));

        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        [HttpPost]
        public ActionResult Create(CourseDTO course)
        {
            #region Crear course
            try
            {
                if (!ModelState.IsValid)
                    return View(course);

                context.Courses.Add(new Course
                {
                    CourseID = course.CourseID,
                    Title = course.Title,
                    Credits = course.Credits

                });
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            #endregion
            return View(course);
        }

        // GET: Courses/Edit
        [HttpGet]
        public ActionResult Edit(int courseid)
        {
            #region Optener id
            var course = context.Courses.Where(x => x.CourseID == courseid)
                                             .Select(x => new CourseDTO
                                             {
                                                 CourseID = x.CourseID,
                                                 Title = x.Title,
                                                 Credits = x.Credits
                                             }).FirstOrDefault();
            #endregion
            return View(course);
        }


        // POST: Courses/Edit
        [HttpPost]
        public ActionResult Edit(CourseDTO course)
        {
            #region Editar curso
            try
            {
                if (!ModelState.IsValid)
                    return View(course);
                var courseModel = context.Courses.FirstOrDefault(x => x.CourseID == course.CourseID);

                //campos que se van a modificar
                //sobreescribo las propiedades del modelo de base de datos
                courseModel.Title = course.Title;
                courseModel.Credits = course.Credits;
                //aplique los cambios en base de datos
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            #endregion
            return View(course);
        }


        // GET: Courses/Delete
        [HttpGet]
        public ActionResult Delete(int courseid)
        {
            if (!context.CourseInstructors.Any(x => x.CourseID == courseid))
            {
                var courseModel = context.Courses.FirstOrDefault(x => x.CourseID == courseid);
                context.Courses.Remove(courseModel);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

University.Web/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using University.BL.Models;
using University.BL.DTOs;
using University.BL.Data;
using System.Linq;
using PagedList;


namespace University.Web.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly UniversityContext context = new UniversityContext();

        // GET: Departments
        [HttpGet]
        public ActionResult Index(int? departmentid, int? pageSize, int? page)
        {
            #region Consluta Deparments
            var query = context.Departments.ToList();

            var deparments = query.Where(x => x.StartDate < DateTime.Now)
                .Select(x => new DepartmentDTO
                {
                    DepartmentID = x.DepartmentID,
                    Name = x.Name,
                    Budget = x.Budget,
                    StartDate = x.StartDate

                }).ToList();
            #endregion
            #region Paginacion
            //Si viene nulo dele 10 por defecto
            pageSize = (pageSize ?? 3);
            //si viene igual por defecto llevelo a la 1 
            page = (page ?? 1);
            ViewBag.pageSize = pageSize;
            #endregion 
            return View(deparments.ToPagedList(page.Value, pageSize.Value));

        }

        [HttpGet]
        public ActionResult Create()
        {
            LoadData();

            return View();
        }

        [HttpPost]
        public ActionResult Create(DepartmentDTO department)
        {
            LoadData();
        
                if (!ModelState.IsValid)
                    return View(department);

                if (department.StartDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");
                context.Departments.Add(new Department
                {
                    Name = department.Name,
                    Budget = department.Budget,
                    StartDate = department.StartDate,
                    InstructorID = department.InstructorID

                });
                context.SaveChanges();

                return RedirectToAction("Index");
            
            
            



        }
        private void LoadData()
        {
            var instructors = context.Instructors.Select(x => new InstructorDTO
            {
                ID = x.ID,
                FirstMidName = x.FirstMidName,
                LastName = x.LastName
            }).ToList();
            ViewData["Instructors"] = new SelectList(instructors, "ID", "FullName");
        }
        [HttpGet]
        public ActionResult Edit(int departmentid)
        {
            LoadData();

            var deparment = context.Departments.Where(x => x.DepartmentID == departmentid)
                                                .Select(x => new DepartmentDTO
                                                {
                                                    DepartmentID = x.DepartmentID,
                                                    Name = x.Name,
                                                    Budget = x.Budget,
                                                    StartDate = x.StartDate,
                                                    InstructorID = x.InstructorID

                                                }).FirstOrDefault();

            return View(deparment);
        }
        [HttpPost]
        public ActionResult Edit(DepartmentDTO department)
        {
            LoadData();

            try
            {
                if (!ModelState.IsValid)
                    return View(department);
                if (department.StartDate > DateTime.Now)
                    throw new Exception("La fecha no puede ser mayor a la fecha actual");
                var departmentModel = context.Departments.FirstOrDefault(x => x.DepartmentID == department.DepartmentID);

                departmentModel.Name = department.Name;
                departmentModel.Budget = department.Budget;
                departmentModel.StartDate = department.StartDate;
                departmentModel.InstructorID = department.InstructorID;
                //aplique cambios
                context.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

            }
            return View(department);


        }

        [HttpGet]

        public ActionResult Delete(int departmentid)
        {
            var departmentModel = context.Departments.FirstOrDefault(x => x.DepartmentID == departmentid);
            context.Departments.Remove(departmentModel);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

    }


}

University.Web/Controllers/OfficeAssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using University.BL.Models;
using University.BL.DTOs;
using University.BL.Data;
using System.Linq;
using PagedList;

namespace University.Web.Controllers
{
    public class OfficeAssignmentsController : Controller
    {
        private readonly UniversityContext context = new UniversityContext();

        // GET: OfficeAssignments
        public ActionResult Index(int? pageSize, int? page)
        {
            //  SELECT * FROM OfficeAssignment
            var query = context.OfficeAssignments.Include("Instructor").ToList();
            var offices = query.Select(x => new OfficeAssignmentDTO
            {
                InstructorID = x.InstructorID,
                Location = x.Location,
                Instructor = new InstructorDTO
                {
                    FirstMidName = x.Instructor.FirstMidName,
                    LastName = x.Instructor.LastName
                }
            });
            #region Paginacion
            //Si viene nulo dele 10 por defecto
            pageSize = (pageSize ?? 3);
            //si viene igual por defecto llevelo a la 1 
            page = (page ?? 1);
            ViewBag.pageSize = pageSize;
            #endregion 
            
            return View(offices.ToPagedList(page.Value, pageSize.Value));
        }

        [HttpGet]
        public ActionResult Create()
        {
            LoadData();

            return View();
        }

        [HttpPost]
        public ActionResult Create(OfficeAssignmentDTO office)
        {
            LoadData();

            if (!ModelState.IsValid)
                return View(ModelState);

            // INSERT INTO OfficeAssignments
            context.OfficeAssignments.Add(new BL.Models.OfficeAssignment
            {
                InstructorID = office.InstructorID,
                Location = office.Location
            });
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        

        private void LoadData()
        {
            var instructors = context.Instructors.Select(x => new InstructorDTO
            {
                ID = x.ID,
                FirstMidName = x.FirstMidName,
                LastName = x.LastName
            }).ToList();
            ViewData["Instructors"] = new SelectList(instructors, "ID", "FullName");
        }



        [HttpGet]
        public ActionResult Edit(int instructorid){

            var offices = context.OfficeAssignments.Where(x => x.InstructorID == instructorid)
                                          .Select(x => new OfficeAssignmentDTO
                                          {
                                              InstructorID = x.InstructorID,
                                              Location = x.Location
                                          }).FirstOrDefault();

            return View(offices);
        }

        [HttpPost]
        public ActionResult Edit(OfficeAssignmentDTO office)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(office);

                var officeModel = context.OfficeAssignments.FirstOrDefault(x => x.InstructorID == office.InstructorID);

                //campos que se van a modificar
                //sobreescribo las propiedades del modelo de base de datos
                officeModel.Location = office.Location;

                //aplique los cambios en base de datos
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(office);
        }


        [HttpGet]
        public ActionResult Delete(int instructorid)
        {
            /*if (!context.OfficeAssignments.Any(x => x.InstructorID == instructorid))
            {*/
            //NO ES NECESARIO VALIDAR ELIMINA DIRECTO
            var officeModel = context.OfficeAssignments.FirstOrDefault(x => x.InstructorID == instructorid);
            context.OfficeAssignments.Remove(officeModel);
            context.SaveChanges();
            //}

            return RedirectToAction("Index");
        }

    }
}

University.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>University</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- Site -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/Content/Site.css">
    <script src="~/Scripts/Site.js"></script>
    <link rel="stylesheet" href="~/Content/PagedList.css" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- ============================================================== -->
        <!-- Sidebar -->
        <!-- ============================================================== -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <img src="~/Assets/angular-icon.svg" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                University
            </div>
            <div class="list-group list-group-flush">

                @Html.ActionLink("Students", "Index", "Students", null, new { @class = "list-group-item list-group-item-action bg-light" })
                @Html.ActionLink("Course", "Index", "Courses", null, new { @class = "list-group-item list-group-item-action bg-light" })
                @Html.ActionLink("Department", "Index", "Departments", null, new { @class = "list-group-item list-group-item-action bg-light" })
                @Html.ActionLink("Instructor", "Index", "Instructors", null, new { @class = "list-group-item list-group-item-action bg-light" })
                @Html.ActionLink("Office Assignment", "Index", "OfficeAssignments", null, new { @class = "list-group-item list-group-item-action bg-light" })


            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page Content -->
        <!-- ============================================================== -->
        <div id="page-content-wrapper">
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <i class="fas fa-align-justify" id="menu-toggle"></i>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    @Html.Partial("_LoginPartial")
                </div>
            </nav>
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Page Content -->
        <!-- ============================================================== -->
    </div>

    <!-- ============================================================== -->
    <!-- Menu Toggle Script -->
    <!-- ============================================================== -->
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>